set-option -g default-shell /usr/bin/fish
set -g mouse on

# Add Vi motions to tmux
setw -g mode-keys vi

# Use Alt + arrow keys to navigate panes
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# Save layout to a file
# bind S save-layout ~/tmux_layouts.txt

# Restore layout from a file
# bind R source-file ~/tmux_layouts.txt

# Install tmux-resurrect plugin
set -g @plugin 'tmux-plugins/tmux-resurrect'

bind x kill-session
